### PR TITLE
Feature/integrate lens identity

### PR DESCRIPTION
**Pull request by fengshanshan**
- add lens to upstream
- remove social tags request from rss3
- use parameter cursor for the pagination of rss3 result

### CODE REVIEW

**Review by nykma — DISMISSED** [review]
Good for now. But could we "reference to" Lens' official GraphQL schema? Or, do we need to write a script to update `src/upstream/lens/schema.graphql` easily?

**Comment by fengshanshan** [comment]
The schema file is download from the official site. The structs are enough for us to use, we can update the schema.graphql manually if   there are some changes in the future

**Comment by fengshanshan** [comment]
> Good for now. But could we "reference to" Lens' official GraphQL schema? Or, do we need to write a script to update `src/upstream/lens/schema.graphql` easily?

The schema file is download from the official site. The structs are enough for us to use, we can update the schema.graphql manually if there are some changes in the future

**Comment by nykma** [comment]
> > Good for now. But could we "reference to" Lens' official GraphQL schema? Or, do we need to write a script to update `src/upstream/lens/schema.graphql` easily?
> 
> The schema file is download from the official site. The structs are enough for us to use, we can update the schema.graphql manually if there are some changes in the future

Good. Write an update script in `justfile` then.

**Review by ZhongFuze — COMMENTED** [review]
Lens-graphql-server authorization is more strict, it will be a Forbidden Error (that is, an error due to Authorization),
gql_client::Client `Cookie` not sent in request
`cynic` transparently transmits all of the headers

**Review by ZhongFuze — APPROVED** [review]

**Comment by fengshanshan** [comment]
> > > Good for now. But could we "reference to" Lens' official GraphQL schema? Or, do we need to write a script to update `src/upstream/lens/schema.graphql` easily?
> > 
> > 
> > The schema file is download from the official site. The structs are enough for us to use, we can update the schema.graphql manually if there are some changes in the future
> 
> Good. Write an update script in `justfile` if this can be done in a single `curl` / `wget`.

sure! done

**Review by nykma — APPROVED** [review]
🉑

**Pull request merged**
